version: "3"

services:

  backend:
    build:
      context: ./maxot_notes/
      dockerfile: Dockerfile
    env_file:
      - ./maxot_notes/.env
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - VIRTUAL_HOST=notes.maxot.xyz
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=notes.maxot.xyz
      - LETSENCRYPT_EMAIL=maxot007@gmail.com

  database:
    image: postgres:12.0-alpine
    healthcheck:
      test: "pg_isready -q -h db"
      interval: 3s
      timeout: 5s
      retries: 5
    env_file:
      - ./maxot_notes/.env
    expose:
      - 5432
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin-local
    image: dpage/pgadmin4:latest
    ports:
      - 5050:5050
    depends_on:
      - database
    env_file:
      - ./pgadmin.env

networks:
  default:
    external:
      name: nginx-proxy